routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/',
    function () {
        return redirect('/home');
    }
);
$this->post('logout', 'Auth\LoginController@logout')->name('logout');


Auth::routes();
Route::group(
    ['middleware' => ['auth']],
    function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::resource('user', 'UserController');
        Route::resource('roster', 'RosterController');
        Route::resource('patient', 'PatientController');
        Route::resource('appointment', 'AppointmentController');
        Route::resource('task', 'TaskController');
        Route::resource('patient.comment', 'AppointmentCommentController');
    }
);

app/Models/Patient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    //
    protected $guarded = [];

    /**
     * Get the user's full name.
     *
     * @return string
     */
    public function getIdentifierAttribute()
    {
        return "#{$this->id}-{$this->name}";
    }

    public function appointments()
    {
        return $this->hasMany(Appointment::class, 'patient_id')->orderBy('id', 'desc');
    }

    public function comments(){
        return $this->hasMany(AppointmentComment::class, 'patient_id')->orderBy('id', 'desc');
    }
}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePatientRequest;
use App\Http\Requests\EditPatientRequest;
use App\Models\Patient;

class PatientController extends Controller
{
    /**
     * Display a listing of Patient.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $patients = Patient::all();

        return view('patient.index', compact('patients'));
    }

    /**
     * Show the form for creating new Patient.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('patient.create');
    }

    /**
     * Store a newly created Patient in storage.
     *
     * @param  \App\Http\Requests\CreatePatientRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePatientRequest $request)
    {
        $patient = Patient::create($request->all());
        if (!$patient) {
            session()->flash('error', "Error creating Patient. Please contact tech department.");

            return redirect()->back();
        }
        session()->flash('success', "Patient Created Successfully");

        return redirect()->route('patient.index');
    }


    /**
     * Show the form for editing Patient.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Patient $patient)
    {
        $relations = [
            'patient' => $patient,
        ];


        return view('patient.edit', $relations);
    }

    /**
     * write brief description
     *
     * @param Patient            $patient
     * @param EditPatientRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Patient $patient, EditPatientRequest $request)
    {
        try {

            $patient->update($request->all());

            session()->flash('success', "Patient information edited Successfully.");

        } catch (\Exception $e) {
            session()->flash('error', "Error updating patient information.");
        }

        return redirect()->route('patient.index');
    }


    /**
     * Display Patient.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $patient = Patient::findOrFail($id);

        return view('patient.show', compact('patient'));
    }


    /**
     * Remove Patient from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $patient = Patient::findOrFail($id);
        $patient->delete();

        return redirect()->route('patient.index');
    }

}

resources/views/patient/create.blade.php
@extends('layouts.app')
@section('page_title', "Patient Management")
@section('content')
	{!! Form::open(['method' => 'POST', 'route' => ['patient.store']]) !!}

	<div class="panel panel-default">
		<div class="panel-heading">
			Create New Patient
		</div>

		<div class="panel-body">
			@include('patient.fields')
			{!! Form::submit("Create New Patient", ['class' => 'btn btn-primary']) !!}
			{!! Form::close() !!}
		</div>

	</div>

@stop

resources/views/patient/edit.blade.php
@extends('layouts.app')
@section('page_title', "Patient Management")
@section('content')
	{!! Form::model($patient, ['method' => 'PUT', 'route' => ['patient.update', $patient->id]]) !!}
	<div class="panel panel-default">
		<div class="panel-heading">
			Edit Staff Profile
		</div>

		<div class="panel-body">
			@include('patient.fields')
			{!! Form::submit("Edit Patient", ['class' => 'btn btn-primary']) !!}
			{!! Form::close() !!}
		</div>
	</div>

@stop

resources/views/patient/fields.blade.php
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
		{!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
		<p class="help-block"></p>
		@if($errors->has('name'))
			<p class="help-block">
				{{ $errors->first('name') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('email', 'Email', ['class' => 'control-label']) !!}
		{!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
		<p class="help-block"></p>
		@if($errors->has('email'))
			<p class="help-block">
				{{ $errors->first('email') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('phone', 'Contact Number*', ['class' => 'control-label']) !!}
		{!! Form::text('phone', old('phone'), ['class' => 'form-control', 'placeholder' => '', 'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('phone'))
			<p class="help-block">
				{{ $errors->first('phone') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('address', 'Address*', ['class' => 'control-label']) !!}
		{!! Form::text('address', old('address'), ['class' => 'form-control', 'placeholder' => '', 'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('address'))
			<p class="help-block">
				{{ $errors->first('address') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('dob', 'DOB', ['class' => 'control-label']) !!}
		{!! Form::text('dob', old('dob'), ['class' => 'form-control', 'placeholder' => '', 'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('dob'))
			<p class="help-block">
				{{ $errors->first('dob') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('history', 'Patient History', ['class' => 'control-label']) !!}
		{!! Form::textArea('history', old('history'), ['class' => 'form-control', 'placeholder' => '',
		'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('history'))
			<p class="help-block">
				{{ $errors->first('history') }}
			</p>
		@endif
	</div>
</div>

resources/views/patient/index.blade.php
@extends('layouts.app')
@section('page_title',"Patient Management")
@section('content')

	<div class="panel panel-default">
		<div class="panel-heading">
			List of Patient
			<div class="actions">
				<a href="{{ route('patient.create') }}"><i class="glyphicon glyphicon-plus-sign"></i> Add New
					Patient</a>
			</div>
		</div>

		<div class="panel-body table-responsive">
			<table class="table table-bordered table-striped" id="datatable">
				<thead>
				<tr>
					<th>#Id</th>
					<th>Name</th>
					<th>Phone</th>
					<th>&nbsp;</th>
				</tr>
				</thead>

				<tbody>

				@forelse ($patients as $patient)
					<tr>
						<td>{{ $patient->id }}</td>
						<td><a href="{{ route('patient.show',[$patient->id]) }}"
							   class="">{{ $patient->name }}</a></td>
						<td>{{ $patient->phone }}</td>
						<td>
							<a href="{{ route('patient.edit',[$patient->id]) }}"
							   class="btn btn-xs btn-info">Edit</a>
							{!! \Form::open(array(
								'style' => 'display: inline-block;',
								'method' => 'DELETE',
								'onSubmit' => "return confirm('Are you sure');",
								'route' => ['patient.destroy', $patient->id])) !!}
							{!! \Form::submit("Delete", array('class' => 'btn btn-xs btn-danger')) !!}
							{!! \Form::close() !!}

						</td>
					</tr>
				@empty
					<tr>
						<td colspan="9">No Data</td>
					</tr>
				@endforelse

				</tbody>
			</table>
		</div>
	</div>
@stop

resources/views/patient/show.blade.php
@extends('layouts.app')
@section("page_title","Patient detail")
@section('content')

	<div class="panel panel-default">
		<div class="panel-heading">
			{{$patient->name}}
			<div class="actions">
				<a href="{{route('appointment.create', ['patient_id'=>$patient->id])}}">Add Appointment</a>/
				<a href="{{route('patient.comment.create', $patient->id)}}">Add Comment</a>
			</div>
		</div>

		<div class="panel-body">
			<div class="row">
				<div class="col-md-9">
					<table class="table table-bordered table-striped">
						<tr>
							<th>Name</th>
							<td>{{ $patient->name }}</td>
						</tr>
						<tr>
							<th>Address</th>
							<td>{{ $patient->address }}</td>
						</tr>
						<tr>
							<th>Phone</th>
							<td>{{ $patient->phone }}</td>
						</tr>
						<tr>
							<th>Email</th>
							<td>{{ $patient->email }}</td>
						</tr>
						<tr>
							<th>DOB</th>
							<td>{{ $patient->dob }}</td>
						</tr>
						<tr>
							<th>Patient History</th>
							<td>{{ $patient->history }}</td>
						</tr>
					</table>
				</div>
			</div><!-- Nav tabs -->
			<ul class="nav nav-tabs" role="tablist">

				<li role="presentation" class="active"><a href="#appointments" aria-controls="appointments" role="tab"
														  data-toggle="tab">Appointments</a></li>
				<li role="presentation"><a href="#findings" aria-controls="findings" role="tab"
										   data-toggle="tab">Finding/Comments</a></li>
			</ul>

			<!-- Tab panes -->
			<div class="tab-content">

				<div role="tabpanel" class="tab-pane active" id="appointments">
					<table class="table table-bordered table-striped">
						<thead>
						<tr>
							<th>Doctor</th>
							<th>Datetime</th>
						</tr>
						</thead>

						<tbody>

						@forelse($patient->appointments()->get() as $appointment)
							<tr>
								<td>{{ $appointment->doctor->name }}</td>
								<td>{{$appointment->date}} ({{$appointment->start_time}} - {{$appointment->end_time}})
								</td>
								<td><a href="{{route('patient.comment.create', [$patient->id,
								'appointment_id'=>$appointment->id])}}"
									   class="btn
								btn-success">Add
										Comment</a></td>
							</tr>
						@empty
						@endforelse
						</tbody>
					</table>
				</div>
				<div role="tabpanel" class="tab-pane" id="findings">

					<table class="table table-bordered table-striped">
						<thead>
						<tr>
							<th>Comment/finding</th>
							<th>Added By</th>
							<th>Added Date</th>
							<th></th>
						</tr>
						</thead>

						<tbody>

						@forelse($patient->comments()->get() as $comment)
							<tr>
								<td>{{ $comment->comments }}</td>
								<td>{{$comment->createdBy->name}}
								</td>
								<td>{{$comment->created_at}}
								</td>
								<td><a href="{{route('patient.comment.edit', [$patient->id, $comment->id])}}" class="btn
								btn-success
								btn-sm">
										Edit</a>
								</td>
							</tr>
						@empty
						@endforelse
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
@stop