routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/',
    function () {
        return redirect('/home');
    }
);
$this->post('logout', 'Auth\LoginController@logout')->name('logout');


Auth::routes();
Route::group(
    ['middleware' => ['auth']],
    function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::resource('user', 'UserController');
        Route::resource('roster', 'RosterController');
        Route::resource('patient', 'PatientController');
        Route::resource('appointment', 'AppointmentController');
        Route::resource('task', 'TaskController');
        Route::resource('patient.comment', 'AppointmentCommentController');
    }
);

resources/views/staff/create.blade.php
@extends('layouts.app')
@section('page_title', "Staff Management")
@section('content')
	{!! Form::open(['method' => 'POST', 'route' => ['user.store']]) !!}

	<div class="panel panel-default">
		<div class="panel-heading">
			Create New Staff Profile
		</div>

		<div class="panel-body">
			@include('staff.fields')
			{!! Form::submit("Create New Staff", ['class' => 'btn btn-primary']) !!}
			{!! Form::close() !!}
		</div>

	</div>

@stop

resources/views/staff/edit.blade.php
@extends('layouts.app')
@section('page_title', "Staff Management")
@section('content')
	{!! Form::model($user, ['method' => 'PUT', 'route' => ['user.update', $user->id]]) !!}
	<div class="panel panel-default">
		<div class="panel-heading">
			Edit Staff Profile
		</div>

		<div class="panel-body">
			@include('staff.fields')
			{!! Form::submit("Edit Staff", ['class' => 'btn btn-primary']) !!}
			{!! Form::close() !!}
		</div>
	</div>

@stop

resources/views/staff/fields.blade.php
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('role_id', 'Staff Type*', ['class' => 'control-label']) !!}
		{!! Form::select('role_id', $roles, old('role_id'), ['class' => 'form-control', 'required' => '']) !!}
		<p class="help-block"></p>
		@if($errors->has('role_id'))
			<p class="help-block">
				{{ $errors->first('role_id') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
		{!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
		<p class="help-block"></p>
		@if($errors->has('name'))
			<p class="help-block">
				{{ $errors->first('name') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('email', 'Email*', ['class' => 'control-label']) !!}
		{!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
		<p class="help-block"></p>
		@if($errors->has('email'))
			<p class="help-block">
				{{ $errors->first('email') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('password', 'Password*', ['class' => 'control-label']) !!}
		{!! Form::password('password', ['class' => 'form-control', 'placeholder' => '']) !!}
		<p class="help-block"></p>
		@if($errors->has('password'))
			<p class="help-block">
				{{ $errors->first('password') }}
			</p>
		@endif
	</div>
</div>

<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('mobile_no', 'Contact Number*', ['class' => 'control-label']) !!}
		{!! Form::text('mobile_no', old('mobile_no'), ['class' => 'form-control', 'placeholder' => '', 'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('mobile_no'))
			<p class="help-block">
				{{ $errors->first('mobile_no') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('address', 'Address*', ['class' => 'control-label']) !!}
		{!! Form::text('address', old('address'), ['class' => 'form-control', 'placeholder' => '', 'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('address'))
			<p class="help-block">
				{{ $errors->first('address') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('qualification', 'Qualification*', ['class' => 'control-label']) !!}
		{!! Form::textArea('qualification', old('qualification'), ['class' => 'form-control', 'placeholder' => '',
		'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('qualification'))
			<p class="help-block">
				{{ $errors->first('qualification') }}
			</p>
		@endif
	</div>
</div>

resources/views/staff/index.blade.php
@extends('layouts.app')
@section('page_title',"Staff Management")
@section('content')

	<div class="panel panel-default">
		<div class="panel-heading">
			List of Staff
			<div class="actions">
				<a href="{{ route('user.create') }}"><i class="glyphicon glyphicon-plus-sign"></i> Add New Staff</a>
			</div>
		</div>

		<div class="panel-body table-responsive">
			<table class="table table-bordered table-striped" id="datatable">
				<thead>
				<tr>
					<th>#Id</th>
					<th>Name</th>
					<th>Email</th>
					<th>Role</th>
					<th>&nbsp;</th>
				</tr>
				</thead>

				<tbody>

				@forelse ($users as $user)
					<tr>
						<td>{{ $user->id }}</td>
						<td>{{ $user->name }}</td>
						<td>{{ $user->email }}</td>
						<td>{{ $user->role->title}}</td>
						<td>
							<a href="{{ route('user.edit',[$user->id]) }}"
							   class="btn btn-xs btn-info">Edit</a>
							{!! \Form::open(array(
								'style' => 'display: inline-block;',
								'method' => 'DELETE',
								'onSubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
								'route' => ['user.destroy', $user->id])) !!}
							{!! \Form::submit("Delete", array('class' => 'btn btn-xs btn-danger')) !!}
							{!! \Form::close() !!}

						</td>
					</tr>
				@empty
					<tr>
						<td colspan="9">No Data</td>
					</tr>
				@endforelse

				</tbody>
			</table>
		</div>
	</div>
@stop