routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/',
    function () {
        return redirect('/home');
    }
);
$this->post('logout', 'Auth\LoginController@logout')->name('logout');


Auth::routes();
Route::group(
    ['middleware' => ['auth']],
    function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::resource('user', 'UserController');
        Route::resource('roster', 'RosterController');
        Route::resource('patient', 'PatientController');
        Route::resource('appointment', 'AppointmentController');
        Route::resource('task', 'TaskController');
        Route::resource('patient.comment', 'AppointmentCommentController');
    }
);

app/Models/Appointment.php
<?php

namespace App\Models;

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    //
    protected $guarded = [];

    public function todays()
    {
        $query = $this->whereDate(
            'date',
            '=',
            Carbon::today()->toDateString()
        );

        if (auth()->user()->isDoctor()) {
            $query->where('user_id', auth()->user()->id);
        }

        return $query;
    }

    public function upcoming()
    {
        $query = $this->whereDate(
            'date',
            '>',
            Carbon::today()->toDateString()
        );

        if (auth()->user()->isDoctor()) {
            $query->where('user_id', auth()->user()->id);
        }

        return $query;
    }

    public function past()
    {
        $query = $this->whereDate(
            'date',
            '<',
            Carbon::today()->toDateString()
        );
        if (auth()->user()->isDoctor()) {
            $query->where('user_id', auth()->user()->id);
        }

        return $query;
    }

    public function patient()
    {
        return $this->belongsTo(Patient::class, 'patient_id');
    }

    public function doctor()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/AppointmentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAppointmentRequest;
use App\Models\Appointment;
use App\Models\Patient;
use App\Models\Roster;
use Illuminate\Http\Request;

class AppointmentController extends Controller
{
    protected $roster;
    protected $appointment;

    public function __construct(Roster $roster, Appointment $appointment)
    {
        $this->roster      = $roster;
        $this->appointment = $appointment;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $appointmentModel = $this->appointment;
        $rosterModel      = $this->roster;

        return view('appointment.index', compact('appointmentModel', 'rosterModel'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'rosters'  => $this->roster->upcoming()->get()->pluck('identifier', 'id')->prepend('Please select', ''),
            'patients' => Patient::get()->pluck('identifier', 'id')->prepend('Please select', ''),
        ];

        return view('appointment.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(CreateAppointmentRequest $request)
    {
        $data            = $request->all();
        $roster          = Roster::find($request->roster_id);
        $data['user_id'] = $roster->user_id;
        $data['date']    = $roster->date;

        $appointment = Appointment::create($data);
        if (!$appointment) {
            session()->flash('error', "Error creating Appointment. Please contact tech department.");

            return redirect()->back();
        }
        session()->flash('success', "Appointment Created Successfully");

        return redirect()->route('appointment.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Appointment $appointment
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Appointment $appointment)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Appointment $appointment
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Appointment $appointment)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Appointment         $appointment
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Appointment $appointment)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Appointment $appointment
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Appointment $appointment)
    {
        //
    }
}

resources/views/appointment/create.blade.php
@extends('layouts.app')
@section('page_title',"Appointment Management")
@section('content')
	{!! Form::open(['method' => 'POST', 'route' => ['appointment.store']]) !!}

	<div class="panel panel-default">
		<div class="panel-heading">
			Create new appointment
		</div>

		<div class="panel-body">
			<div class="row">
				<div class="col-xs-12 form-group">
					{!! Form::label('patient_id', 'Patient*', ['class' => 'control-label']) !!}
					@php
						$patient_id = old('patient_id');

					if(request()->has('patient_id')){
						$patient_id = request()->get('patient_id');
					}
					@endphp
					{!! Form::select('patient_id', $patients, $patient_id, ['class' => 'form-control', 'required'
					 => '']) !!}

					<p class="help-block"></p>
					@if($errors->has('patient_id'))
						<p class="help-block">
							{{ $errors->first('patient_id') }}
						</p>
					@endif
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12 form-group">
					@php
						$roster_id = old('roster_id');

					if(request()->has('roster_id')){
						$roster_id = request()->get('roster_id');
					}
					@endphp
					{!! Form::label('roster_id', 'Doctor Schedule*', ['class' => 'control-label']) !!}
					{!! Form::select('roster_id', $rosters, $roster_id, ['class' => 'form-control', 'required'
					 => '']) !!}

					@if($errors->has('roster_id'))
						<p class="help-block">
							{{ $errors->first('roster_id') }}
						</p>
					@endif
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12 form-group">
					{!! Form::label('start_time', 'Start time*', ['class' => 'control-label']) !!}
					{!! Form::text('start_time', old('start_time'), ['class' => 'form-control timepicker', 'placeholder' => '', 'required' => '']) !!}
					<p class="help-block"></p>
					@if($errors->has('start_time'))
						<p class="help-block">
							{{ $errors->first('start_time') }}
						</p>
					@endif
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 form-group">
					{!! Form::label('end_time', 'Finish time', ['class' => 'control-label']) !!}
					{!! Form::text('end_time', old('end_time'), ['class' => 'form-control timepicker', 'placeholder' =>
					'']) !!}
					<p class="help-block"></p>
					@if($errors->has('end_time'))
						<p class="help-block">
							{{ $errors->first('end_time') }}
						</p>
					@endif
				</div>
			</div>


			<div class="row">
				<div class="col-xs-12 form-group">
					{!! Form::label('comments', 'Comments', ['class' => 'control-label']) !!}
					{!! Form::textarea('comments', old('comments'), ['class' => 'form-control ', 'placeholder' => '']) !!}
					<p class="help-block"></p>
					@if($errors->has('comments'))
						<p class="help-block">
							{{ $errors->first('comments') }}
						</p>
					@endif
				</div>
			</div>
			{!! Form::submit('Create Appointment', ['class' => 'btn btn-primary']) !!}
			{!! Form::close() !!}
		</div>
	</div>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css">

@stop

@section('javascript')
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.js"></script>
	<script>
        $('.timepicker').timepicker({'timeFormat': 'H:i:s'});

	</script>

@stop

resources/views/appointment/edit.blade.php
@extends('layouts.app')
@section('page_title', "Patient Management")
@section('content')
	{!! Form::model($patient, ['method' => 'PUT', 'route' => ['patient.update', $patient->id]]) !!}
	<div class="panel panel-default">
		<div class="panel-heading">
			Edit Staff Profile
		</div>

		<div class="panel-body">
			@include('patient.fields')
			{!! Form::submit("Edit Patient", ['class' => 'btn btn-primary']) !!}
			{!! Form::close() !!}
		</div>
	</div>

@stop

resources/views/appointment/fields.blade.php
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
		{!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
		<p class="help-block"></p>
		@if($errors->has('name'))
			<p class="help-block">
				{{ $errors->first('name') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('email', 'Email', ['class' => 'control-label']) !!}
		{!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
		<p class="help-block"></p>
		@if($errors->has('email'))
			<p class="help-block">
				{{ $errors->first('email') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('phone', 'Contact Number*', ['class' => 'control-label']) !!}
		{!! Form::text('phone', old('phone'), ['class' => 'form-control', 'placeholder' => '', 'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('phone'))
			<p class="help-block">
				{{ $errors->first('phone') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('address', 'Address*', ['class' => 'control-label']) !!}
		{!! Form::text('address', old('address'), ['class' => 'form-control', 'placeholder' => '', 'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('address'))
			<p class="help-block">
				{{ $errors->first('address') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('dob', 'DOB', ['class' => 'control-label']) !!}
		{!! Form::text('dob', old('dob'), ['class' => 'form-control', 'placeholder' => '', 'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('dob'))
			<p class="help-block">
				{{ $errors->first('dob') }}
			</p>
		@endif
	</div>
</div>
<div class="row">
	<div class="col-xs-12 form-group">
		{!! Form::label('history', 'Patient History', ['class' => 'control-label']) !!}
		{!! Form::textArea('history', old('history'), ['class' => 'form-control', 'placeholder' => '',
		'required' =>
		''])
		 !!}
		<p class="help-block"></p>
		@if($errors->has('history'))
			<p class="help-block">
				{{ $errors->first('history') }}
			</p>
		@endif
	</div>
</div>

resources/views/appointment/index.blade.php
@extends('layouts.app')
@section('page_title',"Appointment Management")
@section('content')

	<div class="panel panel-default">
		<div class="panel-heading">
			@if(auth()->user()->isReceptionist())
			<a href="{{route('appointment.create')}}" class="btn btn-success"><i class="fa fa-plus-circle"></i> New
				Appointment</a>

			<a class="btn btn-primary" href="{{ route('patient.create') }}"><i class="glyphicon
			glyphicon-plus-sign"></i> Add New
				Patient</a>
			@endif	

		</div>
		<div class="panel-body table-responsive">
			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active">
					<a href="#today_appointment" aria-controls="today_appointment" role="tab"
					   data-toggle="tab">Today's Appointments</a></li>
				<li role="presentation"><a href="#upcoming_appointments" aria-controls="tests" role="tab"
										   data-toggle="tab">Upcoming Appointments</a></li>
				<li role="presentation"><a href="#upcoming_appointment_dates" aria-controls="tests" role="tab"
										   data-toggle="tab">Available Appointment dates</a></li>
				<li role="presentation"><a href="#past_appointments" aria-controls="tests" role="tab"
										   data-toggle="tab">Past Appointments</a></li>

			</ul>

			<!-- Tab panes -->
			<div class="tab-content">

				<div role="tabpanel" class="tab-pane active" id="today_appointment">
					<table class="table table-bordered table-striped">
						<thead>
						<tr>
							<th>#SN</th>
							<th>Doctor</th>
							<th>Patient</th>
							<th>Time</th>
						</tr>
						</thead>

						<tbody>
						@forelse($appointmentModel->todays()->get() as $appointment)
							<tr>
								<td>{{$appointment->id}}</td>
								<td>{{$appointment->doctor->name}}</td>
								<td><a href="{{route('patient.show',$appointment->patient->id )}}">{{$appointment->patient->name}}</a></td>
								<td>({{$appointment->start_time}} - {{$appointment->end_time}})</td>

								<td><a href="{{route('patient.comment.create', [$appointment->patient->id,
								'appointment_id'=>$appointment->id])}}"
									   class="btn
								btn-success">Add
										Notes</a></td>

							</tr>
						@empty
							<tr>
								<td colspan="4">No appointments for today</td>
							</tr>
						@endforelse
						</tbody>
					</table>
				</div>

				<div role="tabpanel" class="tab-pane" id="upcoming_appointments">
					<table class="table table-bordered table-striped">
						<thead>
						<tr>
							<th>#SN</th>
							<th>Doctor</th>
							<th>Patient</th>
							<th>Time</th>
						</tr>
						</thead>

						<tbody>
						@forelse($appointmentModel->upcoming()->get() as $appointment)
							<tr>
								<td>{{$appointment->id}}</td>
								<td>{{$appointment->doctor->name}}</td>
								<td>{{$appointment->patient->name}}</td>
								<td>{{$appointment->date}} ({{$appointment->start_time}} - {{$appointment->end_time}})
								</td>
							</tr>
						@empty
							<tr>
								<td colspan="4">No appointments for today</td>
							</tr>
						@endforelse
						</tbody>
					</table>
				</div>

				<div role="tabpanel" class="tab-pane" id="upcoming_appointment_dates">
					<table class="table table-bordered table-striped">
						<thead>
						<tr>
							<th>Sno</th>
							<th>Doctor</th>
							<th>DateTime</th>
							<th>Book</th>
						</tr>
						</thead>

						<tbody>
						@forelse($rosterModel->upcoming()->get() as $roster)
							<tr>
								<td>{{$roster->id}}</td>
								<td>{{$roster->staff->name}}</td>
								<td>{{$roster->date}} ({{$roster->start_time}} - {{$roster->end_time}})</td>

								<td>
									<a href="{{route('roster.show', $roster->id)}}"> Detail</a>/
									<a href="{{route('appointment.create',['roster_id'=>$roster->id])}}">Book</a>
								</td>
							</tr>
						@empty
							<tr>
								<td colspan="4">No appointments for today</td>
							</tr>
						@endforelse
						</tbody>
					</table>
				</div>

				<div role="tabpanel" class="tab-pane" id="past_appointments">
					<table class="table table-bordered table-striped">
						<thead>
						<tr>
							<th>Sno</th>
							<th>Doctor</th>
							<th>Patients</th>
							<th>Date</th>
						</tr>
						</thead>

						<tbody>
						@forelse($appointmentModel->past()->get() as $roster)
							<tr>
								<td>{{$appointment->id}}</td>
								<td>{{$appointment->doctor->name}}</td>
								<td>{{$appointment->patient->name}}</td>
								<td>{{$appointment->date}} ({{$appointment->start_time}} - {{$appointment->end_time}})
								</td>
							</tr>
						@empty
							<tr>
								<td colspan="4">No appointments</td>
							</tr>
						@endforelse
						</tbody>
					</table>
				</div>

			</div>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
		 aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					...
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
@stop

resources/views/appointment/show.blade.php
@extends('layouts.app')
@section("page_title","Patient detail")
@section('content')

	<div class="panel panel-default">
		<div class="panel-heading">
			{{$patient->name}}
		</div>

		<div class="panel-body">
			<div class="row">
				<div class="col-md-9">
					<table class="table table-bordered table-striped">
						<tr>
							<th>Name</th>
							<td>{{ $patient->name }}</td>
						</tr>
						<tr>
							<th>Address</th>
							<td>{{ $patient->address }}</td>
						</tr>
						<tr>
							<th>Phone</th>
							<td>{{ $patient->phone }}</td>
						</tr>
						<tr>
							<th>Email</th>
							<td>{{ $patient->email }}</td>
						</tr>
						<tr>
							<th>DOB</th>
							<td>{{ $patient->dob }}</td>
						</tr>
						<tr>
							<th>Patient History</th>
							<td>{{ $patient->history }}</td>
						</tr>
					</table>
				</div>
			</div><!-- Nav tabs -->
			<ul class="nav nav-tabs" role="tablist">

				<li role="presentation" class="active"><a href="#appointments" aria-controls="appointments" role="tab"
														  data-toggle="tab">Appointments</a></li>
				<li role="presentation"><a href="#tests" aria-controls="tests" role="tab"
														  data-toggle="tab">Tests</a></li>
			</ul>

			<!-- Tab panes -->
				{{--<div class="tab-content">--}}

					{{--<div role="tabpanel" class="tab-pane active" id="appointments">--}}
						{{--<table class="table table-bordered table-striped {{ count($appointments) > 0 ? 'datatable' : '' }}">--}}
							{{--<thead>--}}
							{{--<tr>--}}
								{{--<th>@lang('quickadmin.appointments.fields.client')</th>--}}
								{{--<th>@lang('quickadmin.clients.fields.last-name')</th>--}}
								{{--<th>@lang('quickadmin.clients.fields.phone')</th>--}}
								{{--<th>@lang('quickadmin.clients.fields.email')</th>--}}
								{{--<th>@lang('quickadmin.appointments.fields.employee')</th>--}}
								{{--<th>@lang('quickadmin.employees.fields.last-name')</th>--}}
								{{--<th>@lang('quickadmin.appointments.fields.start-time')</th>--}}
								{{--<th>@lang('quickadmin.appointments.fields.finish-time')</th>--}}
								{{--<th>@lang('quickadmin.appointments.fields.comments')</th>--}}
								{{--<th>&nbsp;</th>--}}
							{{--</tr>--}}
							{{--</thead>--}}

							{{--<tbody>--}}
							{{--@if (count($appointments) > 0)--}}
								{{--@foreach ($appointments as $appointment)--}}
									{{--<tr data-entry-id="{{ $appointment->id }}">--}}
										{{--<td>{{ $appointment->client->first_name or '' }}</td>--}}
										{{--<td>{{ isset($appointment->client) ? $appointment->client->last_name : '' }}</td>--}}
										{{--<td>{{ isset($appointment->client) ? $appointment->client->phone : '' }}</td>--}}
										{{--<td>{{ isset($appointment->client) ? $appointment->client->email : '' }}</td>--}}
										{{--<td>{{ $appointment->employee->first_name or '' }}</td>--}}
										{{--<td>{{ isset($appointment->employee) ? $appointment->employee->last_name : '' }}</td>--}}
										{{--<td>{{ $appointment->start_time }}</td>--}}
										{{--<td>{{ $appointment->finish_time }}</td>--}}
										{{--<td>{!! $appointment->comments !!}</td>--}}
										{{--<td>--}}
											{{--@can('appointment_view')--}}
												{{--<a href="{{ route('admin.appointments.show',[$appointment->id]) }}"--}}
												   {{--class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>--}}
											{{--@endcan--}}
											{{--@can('appointment_edit')--}}
												{{--<a href="{{ route('admin.appointments.edit',[$appointment->id]) }}"--}}
												   {{--class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>--}}
											{{--@endcan--}}
											{{--@can('appointment_delete')--}}
												{{--{!! Form::open(array(--}}
													{{--'style' => 'display: inline-block;',--}}
													{{--'method' => 'DELETE',--}}
													{{--'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",--}}
													{{--'route' => ['admin.appointments.destroy', $appointment->id])) !!}--}}
												{{--{!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}--}}
												{{--{!! Form::close() !!}--}}
											{{--@endcan--}}
										{{--</td>--}}
									{{--</tr>--}}
								{{--@endforeach--}}
							{{--@else--}}
								{{--<tr>--}}
									{{--<td colspan="9">@lang('quickadmin.qa_no_entries_in_table')</td>--}}
								{{--</tr>--}}
							{{--@endif--}}
							{{--</tbody>--}}
						{{--</table>--}}
					{{--</div>--}}
				{{--</div>--}}
		</div>
	</div>
@stop